#ifndef __FONTS_COVEREDBYYOURGRACE_REGULAR_H__
#define __FONTS_COVEREDBYYOURGRACE_REGULAR_H__
#include "CoveredByYourGrace_Regular/CoveredByYourGrace_Regular_12pt7b.h"
#include "CoveredByYourGrace_Regular/CoveredByYourGrace_Regular_16pt7b.h"
#include "CoveredByYourGrace_Regular/CoveredByYourGrace_Regular_20pt7b.h"
#include "CoveredByYourGrace_Regular/CoveredByYourGrace_Regular_26pt7b.h"
#include "CoveredByYourGrace_Regular/CoveredByYourGrace_Regular_32pt7b.h"
#include "CoveredByYourGrace_Regular/CoveredByYourGrace_Regular_40pt7b.h"
#include "CoveredByYourGrace_Regular/CoveredByYourGrace_Regular_48pt7b.h"
#include "CoveredByYourGrace_Regular/CoveredByYourGrace_Regular_6pt7b.h"
#endif
